// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD00d3vQoKHiwcpJaVNv3n8mlZC2wRRHs',
    appId: '1:1091731704979:web:1ca9ba4388eb42e97dd166',
    messagingSenderId: '1091731704979',
    projectId: 'travel-buddies-mad-project',
    authDomain: 'travel-buddies-mad-project.firebaseapp.com',
    storageBucket: 'travel-buddies-mad-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKB63Bf1-4FS_bmNAlYPKSPWRCdhHRNE',
    appId: '1:1091731704979:android:88d93613797d68407dd166',
    messagingSenderId: '1091731704979',
    projectId: 'travel-buddies-mad-project',
    storageBucket: 'travel-buddies-mad-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDABMdE9gogs7eu7KcJ2d2ay0eL87ags',
    appId: '1:1091731704979:ios:426d56cefa0457727dd166',
    messagingSenderId: '1091731704979',
    projectId: 'travel-buddies-mad-project',
    storageBucket: 'travel-buddies-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDABMdE9gogs7eu7KcJ2d2ay0eL87ags',
    appId: '1:1091731704979:ios:426d56cefa0457727dd166',
    messagingSenderId: '1091731704979',
    projectId: 'travel-buddies-mad-project',
    storageBucket: 'travel-buddies-mad-project.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD00d3vQoKHiwcpJaVNv3n8mlZC2wRRHs',
    appId: '1:1091731704979:web:662083ad4efb5c157dd166',
    messagingSenderId: '1091731704979',
    projectId: 'travel-buddies-mad-project',
    authDomain: 'travel-buddies-mad-project.firebaseapp.com',
    storageBucket: 'travel-buddies-mad-project.firebasestorage.app',
  );
}
